version: "3.3"
services:

  # RabbitMQ that connects the backend to the frontend
  bladecaller_queue:
    build: ./queue
    ports:
      - "15672:15672"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  # mock_producer:
  #   build: "./mockProducer"
  #   command: "/usr/bin/python3.7 example.py"
  #   expose:
  #     - "5672"

  # bladecaller_database:
  #   build: .
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #     - "./:/home/project"
  #   expose:
  #     - 8000
  #     - 80
  #   ports: 
  #     - '8000:8000'
  #     - '80:80'
  #   volumes: 
  #     - ./:/home/project/
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
  #       delay: 10s
  #       max_attempts: 3
  #       window: 120s

  rakan_engine:
    build: .
    expose:
      - "5672"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    volumes: 
      - "./:/home/project"