# Generated by Django 3.0.6 on 2020-05-26 02:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('mapContents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('compactness', models.FloatField()),
                ('distribution', models.FloatField()),
                ('borderRespect', models.FloatField()),
                ('vra', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('score', 'score'), ('walk', 'walk')], max_length=256)),
                ('jobId', models.CharField(max_length=256, unique=True)),
                ('alpha', models.FloatField()),
                ('beta', models.FloatField()),
                ('gamma', models.FloatField()),
                ('eta', models.FloatField()),
            ],
        ),
    ]
