# Generated by Django 3.0.6 on 2020-05-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='maxSteps',
            field=models.IntegerField(default=200),
        ),
    ]
