# Generated by Django 3.0.6 on 2020-05-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_maxsteps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='maxSteps',
            new_name='steps',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
    ]
