# Generated by Django 3.0.6 on 2020-05-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200526_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, unique=True)),
                ('maxDistricts', models.IntegerField()),
                ('fips', models.IntegerField(unique=True)),
                ('precincts', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('finished', 'finished')], default='finished', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatedmap',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
