# Generated by Django 3.0.6 on 2020-05-26 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200526_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmap',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 26, 22, 48, 42, 864147, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
