# Generated by Django 3.0.6 on 2020-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_state_granularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='granularity',
            field=models.CharField(choices=[('vtd', 'vtd'), ('county', 'county')], default='vtd', max_length=7),
        ),
    ]
