# Generated by Django 3.0.6 on 2020-06-01 00:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_generatedmap_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmap',
            name='md5hash',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generatedmap',
            name='mapContents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
