# Generated by Django 3.0.6 on 2020-05-28 05:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TractBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('land', models.FloatField()),
                ('water', models.FloatField()),
                ('totalPop', models.IntegerField(default=0)),
                ('whitePop', models.IntegerField(default=0)),
                ('blackPop', models.IntegerField(default=0)),
                ('nativeAPop', models.IntegerField(default=0)),
                ('asianPop', models.IntegerField(default=0)),
                ('pacisPop', models.IntegerField(default=0)),
                ('otherPop', models.IntegerField(default=0)),
                ('multiPop', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VTDBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('geoid', models.CharField(max_length=255, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('land', models.FloatField()),
                ('water', models.FloatField()),
            ],
        ),
    ]
