# Generated by Django 3.0.6 on 2020-05-28 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_finished'),
        ('datamerger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtblock',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tractblock',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
        migrations.AlterField(
            model_name='vtdblock',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
