# Generated by Django 3.0.6 on 2020-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerger', '0002_auto_20200528_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtdblock',
            name='county',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vtdblock',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districtblock',
            name='district_id',
            field=models.IntegerField(unique=True),
        ),
    ]
