# Generated by Django 3.0.6 on 2020-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerger', '0003_auto_20200528_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractblock',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
