# Generated by Django 3.0.6 on 2020-05-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerger', '0005_tractblock_geoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtdblock',
            name='majorityPop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vtdblock',
            name='minorityPop',
            field=models.IntegerField(default=0),
        ),
    ]
