# Generated by Django 3.0.6 on 2020-05-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamerger', '0006_auto_20200528_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtdblock',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamerger.DistrictBlock'),
        ),
    ]
