# Generated by Django 3.0.6 on 2020-05-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerger', '0009_auto_20200528_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtdblock',
            name='vtd_state_id',
            field=models.IntegerField(default=-1),
        ),
    ]
